DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   firstName VARCHAR(100) NOT NULL,
   lastName VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   address VARCHAR(200) NOT NULL,
   phone VARCHAR(10) NOT NULL,
   cin VARCHAR(8) NOT NULL,
);
